# Generated by Django 5.2.13 on 2026-05-12 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_module', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='analyse_ia_symptomes',
            field=models.TextField(blank=True, help_text="Analyse suggérée par l'IA pour aider le médecin"),
        ),
        migrations.AddField(
            model_name='medicament',
            name='contre_indications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='posologie_standard_ia',
            field=models.TextField(blank=True, help_text="Guide de posologie suggéré par l'IA"),
        ),
        migrations.AddField(
            model_name='patient',
            name='alerte_sms_envoyee',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChirurgieAssistee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_distance', models.CharField(max_length=200)),
                ('type_intervention', models.CharField(max_length=255)),
                ('statut_robotique', models.CharField(default='Prêt / Connecté', max_length=100)),
                ('flux_video_ia', models.URLField(blank=True, help_text='Lien du flux vidéo assisté par IA')),
                ('date_intervention', models.DateTimeField()),
                ('chirurgien_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chirurgies_locales', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.patient')),
            ],
        ),
    ]
