# Generated by Django 5.2.13 on 2026-05-19 16:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_guidemodule_consultation_analyse_ia_symptomes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='code_facture_unique',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='prix_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
