# Generated by Django 5.2.13 on 2026-05-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_vente_code_facture_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionbancaire',
            name='source',
            field=models.CharField(blank=True, choices=[('PHARMA', 'Pharmacie'), ('HOSPIT', 'Hospitalisation'), ('SMS', 'Service SMS')], default='PHARMA', max_length=10, null=True),
        ),
    ]
