# Generated by Django 5.2.13 on 2026-05-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_transactionbancaire_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='conditionnement_achat',
            field=models.CharField(choices=[('UNITE', 'Unité (Boîte/Flacon)'), ('CARTON', 'Carton de Gros'), ('PALETTE', 'Palette Importation')], default='UNITE', max_length=20),
        ),
        migrations.AddField(
            model_name='medicament',
            name='cout_fret_douane',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Frais de transport et douane appliqués à ce lot', max_digits=10),
        ),
        migrations.AddField(
            model_name='medicament',
            name='numero_lot_import',
            field=models.CharField(blank=True, help_text='Numéro de lot douanier / international', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='pays_origine',
            field=models.CharField(default='International', help_text='Pays de fabrication (Inde, France, Chine, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='medicament',
            name='prix_grossiste_carton',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix spécial par carton pour les dépôts intégrés', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='unites_par_carton',
            field=models.IntegerField(default=1, help_text="Combien d'unités individuelles contient un carton d'importation"),
        ),
        migrations.AddField(
            model_name='vente',
            name='type_vente',
            field=models.CharField(choices=[('DETAIL', 'Vente au Détail'), ('GROS', 'Vente en Gros (Carton)')], default='DETAIL', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, help_text="Prix de vente standard à l'unité", max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='quantite_stock',
            field=models.IntegerField(default=0, help_text='Quantité totale disponible en unités de détail'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='quantite_vendue',
            field=models.PositiveIntegerField(help_text="Nombre d'unités si Détail, nombre de cartons si Gros"),
        ),
    ]
