# Generated by Django 5.2.13 on 2026-06-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_medicament_conditionnement_achat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='contre_indications',
            field=models.TextField(blank=True, help_text="Généré automatiquement par l'IA si laissé vide"),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='posologie_standard_ia',
            field=models.TextField(blank=True, help_text="Généré automatiquement par l'IA si laissé vide"),
        ),
    ]
