# Generated by Django 5.2.13 on 2026-06-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_alter_medicament_contre_indications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmaciePartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la Pharmacie')),
                ('zone_luanda', models.CharField(max_length=100, verbose_name='Quartier / Zone')),
                ('telephone_whatsapp', models.CharField(max_length=50, verbose_name='Numéro WhatsApp (Prospect)')),
                ('est_affiliee', models.BooleanField(default=False, verbose_name='A accepté le conglomérat')),
                ('date_contact', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
