# Generated by Django 5.2.13 on 2026-06-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_pharmaciepartenaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmaciepartenaire',
            name='zone_luanda',
        ),
        migrations.AddField(
            model_name='pharmaciepartenaire',
            name='pays',
            field=models.CharField(choices=[('ANGOLA', 'Angola (Luanda)'), ('RDC', 'République Démocratique du Congo (Kinshasa)')], default='ANGOLA', max_length=20, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='pharmaciepartenaire',
            name='zone_ville',
            field=models.CharField(default='Non spécifié', help_text='Quartier à Luanda ou Commune à Kinshasa (ex: Gombe, Talatona)', max_length=100, verbose_name='Zone / Commune'),
            preserve_default=False,
        ),
    ]
