# Generated by Django 5.2.13 on 2026-07-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_remove_pharmaciepartenaire_zone_luanda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVeille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('lien', models.URLField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('date_publication', models.DateTimeField()),
                ('date_collecte', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.RemoveField(
            model_name='patient',
            name='alerte_sms_envoyee',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_prochain_rdv',
        ),
        migrations.AlterField(
            model_name='medicament',
            name='cout_fret_douane',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Frais de transport et douane', max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='pays_origine',
            field=models.CharField(default='International', help_text='Pays de fabrication', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='prix_grossiste_carton',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente en gros', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='unites_par_carton',
            field=models.IntegerField(default=1, help_text="Combien d'unités individuelles contient un carton"),
        ),
        migrations.AlterField(
            model_name='pharmaciepartenaire',
            name='zone_ville',
            field=models.CharField(help_text='Quartier à Luanda ou Commune à Kinshasa (ex: Gombe, Talatona)', max_length=100),
        ),
    ]
