# Generated by Django 5.2.13 on 2026-07-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_articleveille_remove_patient_alerte_sms_envoyee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleveille',
            name='type_urgence',
            field=models.CharField(default='Normale', max_length=50, verbose_name="Niveau d'urgence"),
        ),
        migrations.AddField(
            model_name='articleveille',
            name='zone',
            field=models.CharField(default='Non spécifié', max_length=100, verbose_name='Zone géographique'),
        ),
    ]
